### PR TITLE
Responsive d

### PR DESCRIPTION
**Pull request by anewman15**
In this PR, we replicated the TNW main site.

We concentrated on the responsive design aspects of the website by figuring out how different divisions of the site responds to different screen sizes.

There were two breakpoints: one at min-width 768px and the other at min-width 1024px.

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @anewman15 and @ElijahTobs 
### You guys have done a good job so far :clap: However, you have a few issues to solve before your application can be approved. 
- Add Logo to the application and if you can make the navigation sticky, that would be great
- On the latest deals, the images are too small on large screen devices
latest deals
- In your html5 file, avoid using the &nbsp; instead, you can achieve this with box-model - margins and paddings
nbps

### Make these changes are resubmit for another review. Good luck.
- Happy coding

By Raymond 
Slack: @iamraymond

**Comment by anewman15** [comment]
Thanks @rOluochKe, we have made the changes

**Review by christianotieno — APPROVED** [review]
# PROJECT APPROVED :champagne:
Excellent job on this project guys. :fireworks:  Keep it up.
##
### The [clone](https://raw.githack.com/ElijahTobs/TNW-clone/responsive-d/index.html) shows good understanding and usage of building with responsive design. :100:
##
- The cloned page is rendering as it should and meets all the project specifications. **Make sure you sort out the z-index issue that is causing some elements to overlap before we merge: Example 👇**
z-index

-  The project has a descriptive README.md and is professionally done. **We just need to add a screenshot of the clone in the README, before merging**.
- Pull Request has a meaningful title and a short description.
- CSS is clean. No linter errors at this point and no bad practices used as well.
- The markup as well has no errors nor warnings to show. Good job with that.
- The repo has followed all the guidelines there are to follow (GitHub flow etc.)
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @anewman15 & @ElijahTobs! :+1:
- When you have done the specified changes, merge to master, you won't have to submit for another code review with this one. I wish you all the very best in your next tasks 🥇 
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

**Comment by anewman15** [comment]
Thanks a lot @christianotieno!

**Pull request merged**
